---
driver:
  name: vagrant
  require_chef_omnibus: true

platforms:
- name: ubuntu-12.04
  run_list:
  - apt

suites:
- name: default
  run_list:
  - recipe[ci::server]
- name: components
  run_list:
  - recipe[ci_test::components]
